config/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings  # 追加
from django.conf.urls.static import static  # 追加
from machine import views  # 追加
from django.urls import include  # 追加

urlpatterns = [
    # ①今回作成するアプリ「todo」にアクセスするURL
    path('machine/', include('machine.urls')),
    # ②何もURLを指定しない場合（machine/views.pyで、自動的に「machine/top_page.html」にアクセスするよう設定済み）
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

machine/urls.py
from django.urls import path
from . import views

from django.contrib import admin  # 追加
from django.views.generic import TemplateView  # 追加

app_name = 'machine'
urlpatterns = [
    path('', TemplateView.as_view(template_name='machine/index.html'), name='index'),
    path('upload/', views.upload, name='upload'),
]

machine/models.py
from django.db import models

# Create your models here.

machine/views.py
from django.shortcuts import render, redirect  # 追加
from PIL import Image  # 追加
import numpy as np  # 追加
import base64  # 追加
import tensorflow as tf  # 追加
import os  # 追加
# from tensorflow.keras.models import Sequential  # 追加


# 学習モデルのロード
model = tf.keras.models.load_model('machine/mnist.h5')
model.summary()


def index(request):
    return render(request, 'machine/index.html')


def mnist(input):

    result = model.predict(input).argmax()
    return result


def upload(request):

    # 画像データの取得
    files = request.FILES.getlist("files[]")

    # 簡易エラーチェック（jpg拡張子）
    for memory_file in files:

        root, ext = os.path.splitext(memory_file.name)

        if ext != '.jpg':

            message = "【ERROR】jpg以外の拡張子ファイルが指定されています。"
            return render(request, 'machine/index.html', {
                "message": message,
            })

    if request.method == 'POST' and files:
        result = []
        labels = []
        for file in files:
            img = Image.open(file)
            gray_img = img.convert('L')
            img = gray_img.resize((28, 28))
            img = np.array(img).reshape(1, 28, 28, 1)
            labels.append(mnist(img))

        for file, label in zip(files, labels):
            file.seek(0)
            file_name = file
            src = base64.b64encode(file.read())
            src = str(src)[2:-1]
            result.append((src, label))

        context = {
            'result': result
        }
        return render(request, 'machine/result.html', context)

    else:
        return redirect('index')

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block page-title %}{% endblock %}</title>

        <!-- css -->
        <link rel="stylesheet" type='text/css' href="{% static 'css/common.css'%}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
        <!-- font -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet">
    </head>
    <body>
        {% block content %}
        <!-- 子テンプレートの内容がIncludeされる -->
        {% endblock %}

        <!-- js -->
        <!--<script src="{% static 'js/common.js' %}"></script>-->
        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    </body>

</html>

templates/machine/index.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}手書き数字 認識AIアプリ{% endblock %}
{% block content %}
<div class="back-img">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <h1 id="title-name">手書き数字 AIアプリ</h1>
    </div>
    <div class="d-flex flex-column">
      <div class="p-2 bd-highlight" style="text-align: center"><img class="sample-img" src="{% static 'img/sample1.jpg' %}" width="130px" height="130px">
      </div>
      <div class="p-2 bd-highlight"><p style="font-size: medium; text-align: center;color: #4C4C4C;">（例: 判定=3）</p>
      </div>   
    </div>
    <div class="row justify-content-center">
      <p style="margin: 10px;color: #4C4C4C;">画像内の手書きされた数字を読み取り、判定します。<br>
      以下の「ファイル選択」よりjpeg画像を選択した上で「判定」ボタンを押してください。画像は複数選択が可能です。<br><br>
      ※注意事項※<br>
      ・黒背景、白文字での画像をご使用ください。<br>
      ・画像サイズを28×28にしていただくことで、より正確な結果を取得できます。
      </p>
    </div>    
    <form action="{% url 'machine:upload' %}" method="POST" enctype="multipart/form-data">
      <div class="row justify-content-center">
        <div class="file-select">
          <input style="color: #4C4C4C;" type="file" name="files[]" multiple>
        </div>        
      </div>
      <div class="row justify-content-center">
        <div class="submit-button">
          <input type="submit" class="btn btn-lg btn-info" value="check!!">
        </div>      
      </div>   
    {% csrf_token %}
    </form>

    {% if message %}
    <div class="row justify-content-center">
      <div class="error-msg">
        <div class="alert alert-danger" role="alert">
          <p><font color="red">{{message}}<br></font> </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}


{% endblock %}

templates/machine/result.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}手書き数字判定AI{% endblock %}
{% block content %}

<div class="back-img">
    <div class="container-fluid" style="background: url({% static 'img/machine-back.jpg' %});">
      <div class="row justify-content-center">
        <h1 id="title-name">result</h1>
      </div>
      {% for data in result %}
        <div class="alert alert-info">
            <div class="d-flex align-items-center justify-content-center">
                <img style="margin: 20px;" src="data:image/jpg;base64,{{data.0}}" width="80" height="80" />
                <p class="lead">【AIの判定結果】<br>画像は<font color=red><b>{{ data.1 }}</font></b>です。</p>
            </div>
        </div>
        {% endfor %} 
    <a class="btn btn-lg btn-secondary"  href="{% url 'index' %}">戻る</a>
</div>
{% endblock %}